### PR TITLE
SEO Optimization v2

### PR DESCRIPTION
**Pull request by brandonkal**
This is the same as #12 but it is rebased on your new master for a cleaner history. I will be adding commits to test logic to not query metaDescription if useSEO is set to false

### CODE REVIEW

**Comment by brandonkal** [comment]
GitHub deleted and closed my branch. Restored and reopened

**Comment by brandonkal** [comment]
@ryanwiemer 

I wrote some changes that disabled fetching Meta Description from contentful.
This works but it still must be defined in the Contentful response even with graphql directives
`metaDescription @include(if: $useMeta)`
GraphQL still requires that the field exist. It would require a change to the contentful plugin to include missing fields in the REST -> GraphQL transformation.

With that limitation it doesn't make much sense to push my changes. It would mean setting the meta description to the site description for all pages which is not good for SEO.

**Comment by brandonkal** [comment]
I'll stop here. Not sure what else could be added. Having a longer description should improve things.

**Comment by brandonkal** [comment]
For those who don't want a meta description commenting out line 124 of the SEO component would be the simplest method to disable it everywhere.

**Comment by ryanwiemer** [comment]
@brandonkal 

This is merged in along with some minor clean up and the new [`export.json`](https://github.com/ryanwiemer/gatsby-starter-gcn/blob/master/contentful/export.json) file. Feel free to test but everything looked good on my end.  

I also added notes to [`v1.1.0`](https://github.com/ryanwiemer/gatsby-starter-gcn/releases/tag/v1.1.0) with some info on how to upgrade if needed. 

Thanks again for working on this. Have a great weekend!

**Pull request merged**
