### PR TITLE
SEO Optimizations, RSS, GA and PWA

### PR DESCRIPTION
**Pull request by brandonkal**
This pull request adds a bunch of features:

1. SEO as a component - adds JSON-LD schema and opengraph tags
2. Google Analytics
3. Sitemap Component
4. Progressive Web App manifest and Offline support
5. Sticky Footer Layout Fix

This PR expects a `MetaDescription` field in the content model for both Pages and Posts. This is used for both meta description and open graph description. At least one page and one post must have a meta description defined in the contentful space. As long as this is the case, the site will build. I added some logic so that if the user leaves the meta description field blank the post excerpt will be used.

A logo is also used as a fallback for the `og:image` meta tag for pages that do not contain a hero image (e.g. about page and index page).

The contentful/export.json file will have to be updated to add the meta description field. I am not sure how you exported it so perhaps you could implement that feature? For the meta description field in the content model it should be a short text field with a character limit of 150 characters.

### CODE REVIEW

**Comment by ryanwiemer** [comment]
@brandonkal, 

Awesome! This looks like some good stuff. A few notes:

1. Yes, I will need to regenerate the `export.json` file since this involves a change to the content model. It is connected with my Contentful account so I can take care of that. 
2. We should also probably add additional notes to the README for this breaking change.
3. Is `UA-47311644-5` your Google Analytics ID in the `siteConfig.js`? Perhaps we should replace it with a placeholder.
4. It's really minor but if you don't mind I can take a stab at a different placeholder logo icon. 

Thanks,
Ryan

**Comment by brandonkal** [comment]
@ryanwiemer 
1. Awesome.
2. I can look into adding some notes to the README

3. `UA-47311644-5` is a placeholder Google Analytics ID. But it may be best to just leave that string empty in the `siteConfig.js`. I'll test to see if that breaks anything.
4. I'm totally up for a different placeholder logo. One of the issues is that it is square - this is good for iOS and Android homescreen icons links shared on Reddit but this doesn't work so well with Facebook as Facebook prefers to crop to a rectangular dimension. So one approach is to define two icons: one for opengraph and one for the app manifest and favicon.

**Comment by ryanwiemer** [comment]
Here is the icon in a square format and using the default Mac font. Would this work?

logo-512

**Comment by brandonkal** [comment]
That actually should work pretty well as it will crop nicely. I am going to remove the "Merge branch 'develop' into PWA-and-SEO" commit as I didn't mean for that to happen here.

**Comment by brandonkal** [comment]
@ryanwiemer I made the requested changes. I updated the readme to mention the new features but it could probably use some edits to help people update. I'm not sure exactly how best to do this.

**Comment by ryanwiemer** [comment]
Hey @brandonkal, 

Thanks again for contributing. This PR is getting a little messy and I need to think over the SEO specific stuff since it is a breaking change. 

Do you mind dividing this out into a couple of different PRs? At the very least let's keep the SEO stuff separate from the other changes. Usually on open source projects its best to keep each PR as simple as possible and focus on a single topic or feature. I need to be better about this as well. 

Let me know if you have any questions. 

Thanks,
Ryan

**Comment by brandonkal** [comment]
Sure thing I do agree on that. It started as SEO and PWA but it ended up as a bunch of things.


I'll try to break it down into:

1. SEO Schema
2. GA
3. Everything else

If that is okay

**Comment by ryanwiemer** [comment]
Yeah that makes sense. Honestly the changes such as Google Analytics, PWA enhancements and the sticky footer fix are less complicated than the SEO stuff and easier to get merged in sooner. So I would start with that.

**Comment by brandonkal** [comment]
@ryanwiemer I have broken the PR into three.

**Comment by ryanwiemer** [comment]
@brandonkal Thanks! If you are done working on these I can take a look at it some time tomorrow or the next day.

**Comment by brandonkal** [comment]
@ryanwiemer Yes it is done! I hope the SEO part makes more sense now that it is seperate.

**Comment by ryanwiemer** [comment]
I'm gonna close this out since it was split up into separate pull requests.

Thanks.

**Pull request closed without merging**
