### PR TITLE
Crafted Typography and YouTube Embeds

### PR DESCRIPTION
**Pull request by brandonkal**
This pull request is mostly typography improvements/tweaks, but I did add a few features that the styling is dependant on.

Headings, font sizes and weights, and margins have been changed for consistant rythm. The content column max width is now slightly wider for the larger font size. Video embeds are also set to this width.

These typography improvements that I made when developing my [blog](https://brandonkalinowski.com) based on the GCN project, but now I believe they will be useful as part of the GCN starter.

I've also included a Typora theme that mirrors the typography here which I find quite useful for drafting and previewing content posts offline.

Additional features included in this pull request:
- Link Catching for links in the markdown content so React Router is used for internal links
- Simple and responsive Youtube embeds using \`youtube: URL\`. Vimeo is also supported with \`vimeo: URL\`
- Autolinked headers
- Added clean command

### CODE REVIEW

**Comment by ryanwiemer** [comment]
@brandonkal thanks for contributing to the repo!

 I'm gonna be a little picky. This PR has a lot going on in it. Some of it I like and some of it adds complexity that I don't think is necessary for this repo. 

I'm mostly interested in this commit: https://github.com/ryanwiemer/gatsby-starter-gcn/pull/35/commits/df1ae6d42cd82e9a1bed51e1fafaf1a5f526e6b1. Would you like to submit a different PR with this content minus the custom prism theme? I'd like to avoid that if possible.  

Let me know what you think.

**Comment by brandonkal** [comment]
Sure, I can do that. Any particular "standard" prism theme you would prefer? I tried to keep the different components seperated by commits to make it easier to cherry pick the parts desired.

Let me know and I'll make another PR in a few days with that gone and I'll clean some things up a bit.

**Comment by ryanwiemer** [comment]
We can just keep the existing prism theme via `require('prismjs/themes/prism.css')`. That way another CSS file is not needed.

**Comment by brandonkal** [comment]
@ryanwiemer 
I have removed the prism theme. I also tested and fixed the 404 page.
I'm thinking you can squash and merge if you like the result to keep the prism theme out of the history. Or if you really want, I can squash and make another branch.

I also cleaned up the markdown reference post here: https://gist.github.com/brandonkal/81aef71276a54536951c0f205797999c

**Comment by ryanwiemer** [comment]
@brandonkal Thanks. 

I may just end up creating a new branch with the cherry picked items that I like to make it easier. 

Prior to doing that what is the typography based on? I see "casper" mentioned so I wasn't sure if you were using a typography boilerplate or something. It looks good although it needs some adjusting. For example I would like the paragraphs to be a little smaller and I don't like the negative letter spacing on headings.

**Comment by brandonkal** [comment]
@ryanwiemer Feel free to add commits to this PR if that works as well.

It is indeed originally based on the Ghost Casper theme v1. That is where the negative letter spacing is inherited. However, I have also made a lot of changes for better rythm and personal preferences. I would agree on removing the negative spacing for headings actually.

You should be able to reduce font size by just changing the base height as everything is relative. You'd probably also want to reduce column width if going with a smaller letter size.

I found this [baseliner chrome extension](https://chrome.google.com/webstore/detail/baseliner/agoopbiflnjadjfbhimhlmcbgmdgldld?hl=en-US) quite useful in getting everything refined.

**Comment by ryanwiemer** [comment]
@brandonkal, 

I am going to close out this PR. I cherry picked some of these commits as part of the release for [`2.0.1`](https://github.com/ryanwiemer/gatsby-starter-gcn/releases/tag/v2.0.1). I will need to circle back on the typography improvements another day when I have more time. 

Thanks again for contributing!

**Pull request closed without merging**
